### ISSUE TITLE
Can't input some moves

### ISSUE THREAD

**Issue by Paalon** [orangain/kifu-notebook#32]
Can't input the 11st move ☗５五角打 in the following kifu because it is recognized as ☗５五角.

```
開始局面
1 ☗７六歩
2 ☖３四歩
3 ☗２二角成
4 ☖同　銀
5 ☗７八金
6 ☖７七角
7 ☗同　桂
8 ☖８四歩
9 ☗４六角
10 ☖８五歩
11 ☗５五角
```

**Comment by orangain** [comment]
@Paalon  Thank you for reporting the issue! I've fixed it and released a new version. Please try it from the [release](https://github.com/orangain/kifu-notebook/releases/tag/2020-04-27).

Note that the latest version 2020-04-27 includes many internal changes. If you meet a problem, please feel free to file a new issue.
